### PR TITLE
Add std.serialization to docs

### PR DESCRIPTION
**Pull request by JesseKPhillips**
These are the make file changes to get docs building for std.serialization.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
I still get the same error:

$ make -f posix.mak html DOC_OUTPUT_DIR=/Users/jacob/development/d/dlang/d-programming-language.org/web/phobos-prerelease DMD=../dmd/src/dmd

make: **\* No rule to make target `/Users/jacob/development/d/dlang/d-programming-language.org/web/phobos-prerelease/std_serialization_attribute.html', needed by`html'.  Stop.

**Comment by JesseKPhillips** [comment]
I think that might be because you are changing DOC_OUTPUT_DIR, there might
be another variable that also needs changing. Or you didn't pull down
changes locally after using gits auto merge. Otherwise "works for me" :)

On Fri, Jun 14, 2013 at 12:42 AM, jacob-carlborg
notifications@github.comwrote:

> I still get the same error:
> 
> $ make -f posix.mak html DOC_OUTPUT_DIR=/Users/jacob/development/d/dlang/
> d-programming-language.org/web/phobos-prerelease DMD=../dmd/src/dmd
> 
> make: **\* No rule to make target /Users/jacob/development/d/dlang/
> d-programming-language.org/web/phobos-prerelease/std_serialization_attribute.html',
> needed byhtml'. Stop.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jacob-carlborg/phobos/pull/1#issuecomment-19443539
> .

## 

Jesse Phillips

**Comment by jacob-carlborg** [comment]
If I don't change DOC_OUTPUT_DIR I get this:

make: **\* No rule to make target `../web/phobos-prerelease/index.html', needed by`html'.  Stop.

I have created that directory. I have pulled your changes.

**Comment by JesseKPhillips** [comment]
The expected setup is to have dlang.org checked out in the parent dir. The
error obviously does not tell you this. (And no, don't check it out as
../web, once you have ../dlang.org the makefile will have rules to build it)

**Comment by jacob-carlborg** [comment]
Oh, I found the problem now. I my repository was still named d-programming-language.org. I didn't know they actually made the name change. Thanks again.

**Pull request merged**
